### ISSUE TITLE
Unable to load .h5 models with latest version of keras

### ISSUE THREAD

**Issue by codeflakes0** [daniellerch/aletheia#19]
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/work/.local/bin/aletheia.py", line 254, in <module>
    main()
  File "/home/work/.local/bin/aletheia.py", line 51, in main
    options.auto.auto()
  File "/home/work/.local/lib/python3.7/site-packages/aletheialib/options/auto.py", line 73, in auto
    nn = load_model(nn, "effnetb0-A-alaska2-outguess")
  File "/home/work/.local/lib/python3.7/site-packages/aletheialib/options/auto.py", line 31, in load_model
    nn.load_model(model_path, quiet=True)
  File "/home/work/.local/lib/python3.7/site-packages/aletheialib/models.py", line 518, in load_model
    self.model.load_weights(model_path)
  File "/home/work/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2361, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/work/.local/lib/python3.7/site-packages/keras/saving/hdf5_format.py", line 711, in load_weights_from_hdf5_group
    str(len(weight_values)) + ' elements.')
ValueError: Layer #0 (named "efficientnetb0" in the current model) was found to correspond to layer efficientnet-b0 in the save file. However the new layer efficientnetb0 expects 312 weights, but the saved weights have 309 elements.

**Comment by daniellerch** [comment]
Please try the new models and open an issue if the problem persists.
