### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpp6ds_puu/data.mat'

### ISSUE THREAD

**Issue by JMIdeaMaker** [daniellerch/aletheia#7]
I get the error in the title when running this (including traceback):

michael@michael-HP-Laptop-14-bw0xx:~/projects/aletheia$ python3 aletheia.py e4s-predict ~/projects/aletheia/models/e4s_srm_bossbase_lsbm0.10_gs.model srm ~/86095525.jpg 

Killed
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 33, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpp6ds_puu/data.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aletheia.py", line 1111, in <module>
    main()
  File "aletheia.py", line 274, in main
    X = feaext.extractor_fn(extractor)(f)
  File "/home/michael/projects/aletheia/aletheialib/feaext.py", line 100, in SRM_extract
    C1 = _extract('SRM', path, params={"channel":1})
  File "/home/michael/projects/aletheia/aletheialib/octave_interface.py", line 146, in _extract
    data=loadmat(data_path)
  File "/home/michael/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/home/michael/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpp6ds_puu/data.mat'
`

I omitted the warnings. any idea what's wrong?

`

**Comment by Call1st0** [comment]
I have very similar issue but with the file clf.mat is missing. I presume it has something to do with the creation of the mat file in models.py line 213 and 214 
        pclf=self.__tmpdir+"/clf.mat"
        savemat(pclf, self.__mat_clf
becuse files train.mat and stego.mat are correctly written in the same temp folder.

When running:
./aletheia/aletheia.py e4s test.fea gcr.fea wm.model 

I get this traceback:

/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/site-packages/hdf5storage/__init__.py:1306: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  f = h5py.File(filename)
error: Xm(2,_): but Xm has size 1x200
Traceback (most recent call last):
  File "/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmppr8lcn1b/clf.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./aletheia/aletheia.py", line 1119, in <module>
    main()
  File "./aletheia/aletheia.py", line 793, in main
    clf.fit(X_train, y_train)
  File "/home/call1st0/Dropbox/Projekti Programiranje/Python/Steganalysis/aletheia/aletheialib/models.py", line 195, in fit
    self.__mat_clf=loadmat(pclf)
  File "/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/call1st0/miniconda3/envs/alethyapy36/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmppr8lcn1b/clf.mat'

**Comment by JMIdeaMaker** [comment]
needed to install octave, octave-image, and octave-signal

**Comment by azxzxx** [comment]
same error           
how can i fix it
